################################################################################
# Automatically-generated file. Do not edit!
################################################################################

S79_SRCS := 
ASM_SRCS := 
CPP_SRCS := 
S79_UPPER_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
autogen \
autogen/zap-generated \
autogen/zap-generated/attributes \
gecko_sdk_4.4.3/hardware/board/src \
gecko_sdk_4.4.3/hardware/driver/memlcd/src/memlcd_usart \
gecko_sdk_4.4.3/hardware/driver/memlcd/src \
gecko_sdk_4.4.3/hardware/driver/mx25_flash_shutdown/src/sl_mx25_flash_shutdown_usart \
gecko_sdk_4.4.3/platform/CMSIS/RTOS2/Source \
gecko_sdk_4.4.3/platform/Device/SiliconLabs/EFR32MG24/Source \
gecko_sdk_4.4.3/platform/bootloader/api \
gecko_sdk_4.4.3/platform/bootloader/app_properties \
gecko_sdk_4.4.3/platform/common/src \
gecko_sdk_4.4.3/platform/common/toolchain/src \
gecko_sdk_4.4.3/platform/driver/button/src \
gecko_sdk_4.4.3/platform/driver/leddrv/src \
gecko_sdk_4.4.3/platform/emdrv/dmadrv/src \
gecko_sdk_4.4.3/platform/emdrv/gpiointerrupt/src \
gecko_sdk_4.4.3/platform/emdrv/nvm3/src \
gecko_sdk_4.4.3/platform/emdrv/uartdrv/src \
gecko_sdk_4.4.3/platform/emlib/src \
gecko_sdk_4.4.3/platform/middleware/glib/dmd/display \
gecko_sdk_4.4.3/platform/middleware/glib/fonts \
gecko_sdk_4.4.3/platform/middleware/glib/glib \
gecko_sdk_4.4.3/platform/peripheral/src \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/pa-conversions \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/rail_util_built_in_phys/efr32xg24 \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/rail_util_built_in_phys \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/rail_util_power_manager_init \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/rail_util_pti \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/rail_util_rssi \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/rail_util_sequencer \
gecko_sdk_4.4.3/platform/security/sl_component/se_manager/src \
gecko_sdk_4.4.3/platform/security/sl_component/sl_mbedtls_support/src \
gecko_sdk_4.4.3/platform/security/sl_component/sl_protocol_crypto/src \
gecko_sdk_4.4.3/platform/security/sl_component/sl_psa_driver/src \
gecko_sdk_4.4.3/platform/service/device_init/src \
gecko_sdk_4.4.3/platform/service/hfxo_manager/src \
gecko_sdk_4.4.3/platform/service/iostream/src \
gecko_sdk_4.4.3/platform/service/mpu/src \
gecko_sdk_4.4.3/platform/service/power_manager/src \
gecko_sdk_4.4.3/platform/service/sleeptimer/src \
gecko_sdk_4.4.3/platform/service/system/src \
gecko_sdk_4.4.3/platform/service/udelay/src \
gecko_sdk_4.4.3/protocol/bluetooth/src \
gecko_sdk_4.4.3/protocol/openthread/platform-abstraction/efr32 \
gecko_sdk_4.4.3/protocol/openthread/src/cli \
gecko_sdk_4.4.3/util/plugin/security_manager \
gecko_sdk_4.4.3/util/silicon_labs/silabs_core/memory_manager \
gecko_sdk_4.4.3/util/third_party/freertos/cmsis/Source \
gecko_sdk_4.4.3/util/third_party/freertos/kernel \
gecko_sdk_4.4.3/util/third_party/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure \
gecko_sdk_4.4.3/util/third_party/freertos/kernel/portable/SiliconLabs \
gecko_sdk_4.4.3/util/third_party/mbedtls/library \
gecko_sdk_4.4.3/util/third_party/openthread/examples/apps/cli \
gecko_sdk_4.4.3/util/third_party/openthread/examples/platforms/utils \
gecko_sdk_4.4.3/util/third_party/openthread/src/cli \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/api \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/backbone_router \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/border_router \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/coap \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/common \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/crypto \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/diags \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/instance \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/mac \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/meshcop \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/net \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/radio \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/thread \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/utils \
gecko_sdk_4.4.3/util/third_party/openthread/third_party/tcplp/bsdtcp/cc \
gecko_sdk_4.4.3/util/third_party/openthread/third_party/tcplp/bsdtcp \
gecko_sdk_4.4.3/util/third_party/openthread/third_party/tcplp/lib \
gecko_sdk_4.4.3/util/third_party/segger/systemview/SEGGER \
matter_2.2.2/examples/common/QRCode/repo/c \
matter_2.2.2/examples/platform/silabs \
matter_2.2.2/examples/platform/silabs/display \
matter_2.2.2/examples/platform/silabs/efr32 \
matter_2.2.2/examples/platform/silabs/provision \
matter_2.2.2/examples/providers \
matter_2.2.2/examples/shell/shell_common \
matter_2.2.2/src/access \
matter_2.2.2/src/access/examples \
matter_2.2.2/src/app \
matter_2.2.2/src/app/MessageDef \
matter_2.2.2/src/app/clusters/access-control-server \
matter_2.2.2/src/app/clusters/administrator-commissioning-server \
matter_2.2.2/src/app/clusters/basic-information \
matter_2.2.2/src/app/clusters/bindings \
matter_2.2.2/src/app/clusters/descriptor \
matter_2.2.2/src/app/clusters/diagnostic-logs-server \
matter_2.2.2/src/app/clusters/ethernet-network-diagnostics-server \
matter_2.2.2/src/app/clusters/fixed-label-server \
matter_2.2.2/src/app/clusters/general-commissioning-server \
matter_2.2.2/src/app/clusters/general-diagnostics-server \
matter_2.2.2/src/app/clusters/group-key-mgmt-server \
matter_2.2.2/src/app/clusters/groups-server \
matter_2.2.2/src/app/clusters/icd-management-server \
matter_2.2.2/src/app/clusters/identify-server \
matter_2.2.2/src/app/clusters/localization-configuration-server \
matter_2.2.2/src/app/clusters/network-commissioning \
matter_2.2.2/src/app/clusters/operational-credentials-server \
matter_2.2.2/src/app/clusters/ota-requestor \
matter_2.2.2/src/app/clusters/software-diagnostics-server \
matter_2.2.2/src/app/clusters/switch-server \
matter_2.2.2/src/app/clusters/thread-network-diagnostics-server \
matter_2.2.2/src/app/clusters/time-format-localization-server \
matter_2.2.2/src/app/clusters/time-synchronization-server \
matter_2.2.2/src/app/clusters/user-label-server \
matter_2.2.2/src/app/clusters/wifi-network-diagnostics-server \
matter_2.2.2/src/app/icd \
matter_2.2.2/src/app/reporting \
matter_2.2.2/src/app/server \
matter_2.2.2/src/app/util \
matter_2.2.2/src/ble \
matter_2.2.2/src/controller \
matter_2.2.2/src/credentials \
matter_2.2.2/src/credentials/attestation_verifier \
matter_2.2.2/src/credentials/examples \
matter_2.2.2/src/credentials/tests \
matter_2.2.2/src/crypto \
matter_2.2.2/src/inet \
matter_2.2.2/src/lib/address_resolve \
matter_2.2.2/src/lib/asn1 \
matter_2.2.2/src/lib/core \
matter_2.2.2/src/lib/dnssd \
matter_2.2.2/src/lib/shell \
matter_2.2.2/src/lib/shell/commands \
matter_2.2.2/src/lib/support \
matter_2.2.2/src/lib/support/logging \
matter_2.2.2/src/lib/support/verhoeff \
matter_2.2.2/src/messaging \
matter_2.2.2/src/platform \
matter_2.2.2/src/platform/FreeRTOS \
matter_2.2.2/src/platform/OpenThread \
matter_2.2.2/src/platform/silabs \
matter_2.2.2/src/platform/silabs/efr32 \
matter_2.2.2/src/platform/silabs/platformAbstraction \
matter_2.2.2/src/protocols \
matter_2.2.2/src/protocols/bdx \
matter_2.2.2/src/protocols/echo \
matter_2.2.2/src/protocols/interaction_model \
matter_2.2.2/src/protocols/secure_channel \
matter_2.2.2/src/protocols/user_directed_commissioning \
matter_2.2.2/src/setup_payload \
matter_2.2.2/src/system \
matter_2.2.2/src/tracing \
matter_2.2.2/src/transport \
matter_2.2.2/src/transport/raw \
src \

